### ISSUE TITLE
feat: RN with expo image picker를 통해 고른 사진 서버에 보내기

### ISSUE THREAD

**Issue by jeoneunjin** [ID-Buddy/IDBuddy#1]
**Describe the bug**
image picker로 사진을 고른 후 flask 서버로 보낼 때, 업로드 오류: [AxiosError: Request failed with status code 400] 발생, fetch 방식도 마찬가지로 에러 400 발생

**To Reproduce**
1. register 화면으로 이동
2. 프로필 추가 버튼 클릭
3. image picker로 사진 불러오기
4. 사진 등록 버튼 클릭
5. 에러 400발생

**Expected behavior**
'사진 등록' 버튼을 눌렀을 때 정상적으로 서버에 사용자가 고른 이미지가 전송되어야 함. 

**Screenshots**
![Group 20](https://github.com/user-attachments/assets/82069841-186e-4da3-96ef-bf7cd9bbc7b3)

>  이미지 피커로 고른 이미지의 uri 값을 console log로 확인 함. 이미지는 정상적으로 선택되지만, 서버에 전송하려 하면 에러 400이 발생

**Additional context**

**Comment by jeoneunjin** [comment]
RNBlobUtil.wrap()로 인해 imagepicker로 image를 골랐을 때 해당 image의 uri 앞에 "file://"이 붙음. 이걸 없애야 정상적으로 보내질 거라고 함
[출처]https://github.com/RonRadtke/react-native-blob-util/issues/150#issuecomment-1376504218

**Comment by jeoneunjin** [comment]
"file://"을 제거해도 서버에서 image missing 된 상태인 걸 확인 함. blob 객체로 변환하면서 문제가 발생한 것으로 예상되어 fetch대신 XMLHttpRequest를 이용하여 blob 객체로 변환해야 될 것 같음

**Comment by jeoneunjin** [comment]
blob 객체로 변환하지 않고 JSON형식으로 값을 FormData에 추가하여 보냈더니 정상적으로 서버로 업로드 되었음.  단, formData append에 값을 string이나 blob 객체만 써야 하기 때문에 JSON 문자열로 변환 후 append 하였음

**Comment by jeoneunjin** [comment]
JSON 문자열로 변환해서 보냈더니 실패함. JSON형식으로 작성하면 정상적으로 되는데 왜 안 되는지 더 찾아봐야 될 것 같음

**Comment by FTCHD** [comment]
could you post an example of how you're sending a file using `rn-fetch-blob-utils`? ty
